### ISSUE TITLE
v2 API Change in naming

### ISSUE THREAD

**Issue by CHASbotGIT** [gitfrosh/lotr-api#10]
I'd like to say a BIG thank you for this API (bought you a coffee). I'm a volunteer for a hospice charity that has a geeky fund-raising team - the LOTR API is called from a messenger chatbot. I cut over to the V2 api and I noted a couple of small differences - the JSON now returns with characters with the tag 'Name' instead of 'name', and 'Url' instead of 'wikiUrl'.
<img width="545" alt="Screenshot 2020-08-31 at 21 57 29" src="https://user-images.githubusercontent.com/32416795/91768063-fdb03880-ebd4-11ea-827e-2dde0f502008.png">

**Comment by gitfrosh** [comment]
Hi there,

thanks for taking the time and sharing your findings! Unfortunately, these changes were not intended, so I appreciate your investigation even more. I recently updated the API: Characters are now again returned with a "name" and a "wikiUrl".

_PS. Thanks a lot for the coffee! :coffee:  
Your bot project is adorable - if you there's a project (and/or code repo) page available I'd love to add a link on the LotR API docs!_
