### ISSUE TITLE
Migrate code to TypeScript - backend - backend

### ISSUE THREAD

**Issue by MateuszKikmunter** [gitfrosh/lotr-api#100]
It would be beneficial to migrate existing code base to TypeScript to introduce type safety and other features this language provide.

@gitfrosh please let me know what do you think about it.

**Comment by gitfrosh** [comment]
Hey @MateuszKikmunter, I think this would be awesome! Unfortunately, I started the project before I fell in love with Typescript ;) Though it's a huge change and lots of work, I'd be happy to see it in our frontend and backend code. 🚀

**Comment by MateuszKikmunter** [comment]
No problem, I’ll start working on it sometime soon @gitfrosh 🙂

**Comment by AdamCMacKinnon** [comment]
@MateuszKikmunter Would be happy to help!

**Comment by MateuszKikmunter** [comment]
No problem @AdamCMacKinnon. I didn't start working on it yet as I'm pretty busy but will you know once I do. :)

**Comment by MateuszKikmunter** [comment]
Started working on backend code migration, looks like it works but need to fix tests and few other minor things - then will move to frontend and create a separate issue for this part and sample app.

FYI @gitfrosh

**Comment by MateuszKikmunter** [comment]
This part is done and others will be handled [here](https://github.com/gitfrosh/lotr-api/issues/118).
