### ISSUE TITLE
Rings of Power

### ISSUE THREAD

**Issue by davidnormo** [gitfrosh/lotr-api#104]
Just wondering if there were any plans to add Rings of Power content to the API or not?

**Comment by gitfrosh** [comment]
Hi @davidnormo, interesting question, thank you! I just checked, and the LotR wiki marks RoP entries (e.g., https://lotr.fandom.com/wiki/Arondir) as non-canon, so my feeling would be to leave them out, but I'm open to discussion.
Any thoughts @MateuszKikmunter @EddieEldridge or anybody?

**Comment by MateuszKikmunter** [comment]
I actually think the same @gitfrosh, if they’re marked as non-canon, better leave them out and stick to the original content.

**Comment by gitfrosh** [comment]
Closing this for now.
