### ISSUE TITLE
I'm begging you to change Bearer Token to Bearer Tolkien

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [gitfrosh/lotr-api#113]
So I can sleep at night.

**Comment by btamilio** [comment]
I might also suggest changing the Authorization type from _Bearer_ to _Ring-Bearer_. Combined with @michaelfromtheoutfit's suggestion, this might look like:

Authorization: Ring-Bearer <Tolkien>

**Comment by michaelfromtheoutfit** [comment]
![](https://media.giphy.com/media/WNwErIxqX18xmm92UX/giphy.gif)

@btamilio

**Comment by gitfrosh** [comment]
That’s a novel idea, but I'm not ready for 500-page documentation ;)
