### ISSUE TITLE
First and Second Age

### ISSUE THREAD

**Issue by Victor-Palha** [gitfrosh/lotr-api#126]
It would be interesting if the API included information about the First and Second Age of Middle-earth. I'm curious if I can contribute this information or if it would be limited by copyright.

**Comment by gitfrosh** [comment]
There are no limitations on adding data based on the different Ages of Middle-earth. Contributions with original content or references from public domain sources are definitely welcome! PRs welcome :)

**Comment by Victor-Palha** [comment]
Alright, thanks buddy!
