### ISSUE TITLE
Heroku App not responding

### ISSUE THREAD

**Issue by ghvaldez** [gitfrosh/lotr-api#149]
Looks like the app is gone or has moved from the documented location.  https://the-one-api.herokuapp.com/

![Screenshot 2024-08-14 4 05 50 PM](https://github.com/user-attachments/assets/56951ee3-31f3-445b-8af0-638c33dbcc1c)

**Comment by MateuszKikmunter** [comment]
App has been moved [here](https://github.com/gitfrosh/lotr-api?tab=readme-ov-file#important-note), it’s in the readme.

**Comment by ghvaldez** [comment]
Thanks.  Sorry, should have read the readme more closely.  The v2 seems to work as intended.  I got here to this repo in a round about way from https://documenter.getpostman.com/view/5940/T1LPDmq5#the-one-api-to-rule-them-all.  This issue can be closed.
