### ISSUE TITLE
Add PWA support to the-one-api.dev

### ISSUE THREAD

**Issue by gitfrosh** [gitfrosh/lotr-api#15]
The _The one API_ documentation website (https://the-one-api.dev) is not yet PWA ready.

- see https://web.dev/progressive-web-apps for more info
- task would include adding a manifest, service worker and others

Any help is appreciated! :rocket:

**Comment by vanshaj234** [comment]
Hi, I would like to help but could please explain to me what all I have to do .
Like You want to make a manifest file for the one api.dev?
`{
  "name": "The One API",
  "theme_color": "#2196f3",
  "background_color": "#2196f3",
  "display": "browser",
  "scope": "/",
  "start_url": "/https://the-one-api.dev/"
}`
Like this you want !!

**Comment by gitfrosh** [comment]
There are some (more) requirements, that would mark _the-one.api.dev_ as a PWA, one of them is adding a manifest. The Chrome extension Lighthouse (https://developers.google.com/web/ilt/pwa/lighthouse-pwa-analysis-tool) is a great tool to check if all requirements are fulfilled. If you feel confident, you may add a pull request to this issue. Thanks!

**Comment by gabrielclaudino** [comment]
Hello, I can help with this issue 😀
