### ISSUE TITLE
Missing Dialog in CSV File

### ISSUE THREAD

**Issue by Yag000** [gitfrosh/lotr-api#151]
The quote with ID `5cd96e05de30eff6ebccf00c` at [line 2077](https://github.com/gitfrosh/lotr-api/blob/beta/db/csv/quotes.csv?plain=1#L2077) in the csv file has no dialog text. Is this intentional, or should it be updated with the correct dialog?

**Comment by MateuszKikmunter** [comment]
No idea about this one tbh, maybe @gitfrosh will know?

**Comment by gitfrosh** [comment]
Looks like an unintentionally empty quote by Treebeard in the Two Towers - can possibly be removed, PR welcome! :) (also for other occurrences of empty quotes)
