### ISSUE TITLE
Blocking spam / bulk registrations

### ISSUE THREAD

**Issue by gitfrosh** [gitfrosh/lotr-api#26]
Sometimes we monitor bulk registrations on the-one-api.dev, triggered by the same IP within a very short period if time. It would be great to implement a basic security mechanism, that prevents spam registrations like that.

Feel free to create a pull request! 🚀

**Comment by MateuszKikmunter** [comment]
Hi @gitfrosh, could please provide more details about this issue? Is it still happening? What is the IP which is sending those requests? I would like to take a look at this issue if that's OK.

**Comment by MateuszKikmunter** [comment]
I think that basic rate limiting will do the job. If that’s fine with you, I’ll produce a PR soon.
