### ISSUE TITLE
Quote API for LOTR trilogy is not returning any quote

### ISSUE THREAD

**Issue by aliasgerkw** [gitfrosh/lotr-api#28]
Get https://the-one-api.dev/v2/movie/5cd96e05de30eff6ebcce7e9/quote

Response
{
    "docs": [],
    "total": 0,
    "limit": 1000,
    "offset": 0,
    "page": 1,
    "pages": 1
}

**Comment by gitfrosh** [comment]
Hi there, yes, you're right. This endpoint refers to "The Desolation of Smaug", whose quotes are not (yet) available in the API. Only the original Lord of the Rings trilogy quotes can be fetched, e.g. https://the-one-api.dev/v2/movie/5cd95395de30eff6ebccde5b/quote
Will add a small info in the documentation soon!
greetings, rike

**Comment by aliasgerkw** [comment]
Oh cool. Thanks @gitfrosh
