### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by gitfrosh** [gitfrosh/lotr-api#29]
This Repo is entirely non-tested. 😭 
Pull requests including 
- a CRA / jest / react-testing-library setup and some unit tests for the frontend
- a test setup for the backend

are very welcome.

**Comment by MateuszKikmunter** [comment]
Hey, I might look into backend tests. I already added few in my other [PR](https://github.com/gitfrosh/lotr-api/pull/53)  and can continue working on that.

**Comment by EddieEldridge** [comment]
Once the tests are in we should look at adding some basic CI, either with GitHub Actions/CircleCI/Travis or something similar. It would help a lot with reviewing future PRs.

**Comment by MateuszKikmunter** [comment]
Agree, it would be beneficial. Maybe it's worth to create another issue?

**Comment by EddieEldridge** [comment]
> Agree, it would be beneficial. Maybe it's worth to create another issue?

Yep, good idea. See https://github.com/gitfrosh/lotr-api/issues/54

**Comment by MateuszKikmunter** [comment]
Added frontend tests and now api finally should have a valuable suite of tests. (unit for now)
I'm closing this issue as with [this PR](https://github.com/gitfrosh/lotr-api/pull/145) we have enough tests at the moment.
