### ISSUE TITLE
Endpoint does not exist

### ISSUE THREAD

**Issue by konsoul** [gitfrosh/lotr-api#63]
https://the-one-api.dev/v2/ -- Endpoint does not exist error. 

Also, when calling from python using response.raise_for_status() I get a 404 Client Error: Not Found for url.

**Comment by gitfrosh** [comment]
Hi @konsoul, https://the-one-api.dev/v2/ only serves as the base URL for the API. For data access, you should use a specific endpoint (as an example, start with https://the-one-api.dev/v2/book). Further endpoints are listed in the documentation: https://the-one-api.dev/documentation.

Hope this helps!
Best, Rike

**Comment by konsoul** [comment]
Oh my goodness thank you!  I am still new to all this stuff, and sometimes just read over key words like “prefixed” lol.  That helps a bunch thanks again. Sent from Mail for Windows From: RikeSent: Thursday, February 10, 2022 12:49 AMTo: gitfrosh/lotr-apiCc: Brad Rappa; MentionSubject: Re: [gitfrosh/lotr-api] Endpoint does not exist (Issue #63) Hi @konsoul, https://the-one-api.dev/v2/ only serves as the base URL for the API. For data access, you should use a specific endpoint (as an example, start with https://the-one-api.dev/v2/book). Further endpoints are listed in the documentation: https://the-one-api.dev/documentation.Hope this helps!Best, Rike—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>
