### ISSUE TITLE
Rate limited after 2 requests

### ISSUE THREAD

**Issue by MTyson** [gitfrosh/lotr-api#69]
Just trying to hit the api after signing up for auth token and after a couple requests I'm getting 429 too many requests.

GET https://the-one-api.dev/v2/book 429 (Too Many Requests)

**Comment by MateuszKikmunter** [comment]
This works as expected, got 429 only after 100 requests.
![Capture](https://user-images.githubusercontent.com/38324997/159185941-b5d8205a-0f7a-4621-a528-9532f24633c5.PNG)
Before that, I got correct response, but I can take a look at this issue anyway later on.
Only register endpoint will return after few requests to avoid bulk registrations.

**Comment by MateuszKikmunter** [comment]
This works fine and issue can be closed @gitfrosh

**Comment by gitfrosh** [comment]
Thanks for clarifying, @MateuszKikmunter!
