### ISSUE TITLE
#Hacktoberest Idea - I could add /random to quotes or characters, to return a random character or quote!

### ISSUE THREAD

**Issue by 1RedOne** [gitfrosh/lotr-api#81]
Not sure if you're interested in accepting Hacktoberfest requests, but I could give this a go.

I am not at all familiar with this language but have been an fullstack dev for five years now :)

**Comment by gitfrosh** [comment]
Hi @1RedOne, yes we're totally open for #Hacktoberfest pull requests. :) I think a random quote endpoint would be a great addition, it could go under /quotes/random and return a quote object like we already know:
 {
            "_id": "5cd96e05de30eff6ebcce808",
            "dialog": "Oh no, I'm not hungry, leastways not for lembas bread.",
            "movie": "5cd95395de30eff6ebccde5d",
            "character": "5cd99d4bde30eff6ebccfd0d",
 }
 Good luck!

**Comment by MateuszKikmunter** [comment]
@1RedOne are still interested in this idea? Otherwise I'd like to take a look at it soon. :)
