### ISSUE TITLE
Improving Github Repo starter page / README

### ISSUE THREAD

**Issue by gitfrosh** [gitfrosh/lotr-api#82]
The project's current main README is a little bit scarce and not really inviting.

![image](https://user-images.githubusercontent.com/5777874/196365646-4fd70e15-8937-4180-b36c-ca6f051827e2.png)

It would be great to have an improved version. This works as inspiration: https://github.com/othneildrew/Best-README-Template

Possible #hacktoberfest task!

**Comment by Os51** [comment]
Hi! 👋 
I'd be interested in helping with this if you need someone to take this on. Just let me know! 
Thank you

**Comment by gitfrosh** [comment]
Hey @Os51, yes that would be awesome! Good luck with working on this 💪

**Comment by gitfrosh** [comment]
🚀
